apiVersion: apps/v1
kind: Deployment
metadata:
  name: cody-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cody-api
  template:
    metadata:
      labels:
        app: cody-api
    spec:
      containers:
        - name: cody-api
        # This image is going to be the path to the image you create in a future step
          image: us-docker.pkg.dev/scrum-team6/cody-api/api-test
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".1"
              memory: "80Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            failureThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 10
          startupProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 10